In [1]:
import numpy as np

### Scalar


In [4]:
s = 5
s

5

### Vector

In [3]:
v = np.array([5,-2,4])
v

array([ 5, -2,  4])

### Matrices


In [6]:
m = np.array([[5,12,6],[-3,0,14]])
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

### Data types


In [9]:
s_array = np.array(5)
type(s_array)

numpy.ndarray

### Data shapes

In [10]:
m.shape

(2, 3)

In [11]:
v.shape

(3,)

In [19]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [13]:
s_array.shape

()

### Tensors

Generalization of scalars, vectors, matrices, and other data types
* Rank 0: scalar
* Rank 1: vector
* Rank 2: matrix
* Rank 3: 3d object

In [21]:
m1 = np.array([[5,12,6],[-3,0,14]])
m2 = np.array([[9,8,7],[-3,3,5]])


In [22]:
t = np.array([m1,m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [-3,  3,  5]]])

In [23]:
t.shape

(2, 2, 3)

In [24]:
m1 + m2

array([[14, 20, 13],
       [-6,  3, 19]])

In [25]:
m1-m2

array([[-4,  4, -1],
       [ 0, -3,  9]])

In [26]:
m1 + 10

array([[15, 22, 16],
       [ 7, 10, 24]])

In [27]:
v+3

array([8, 1, 7])

### Transpose

In [28]:
m1.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [30]:
v.T

array([ 5, -2,  4])

### Multiplication (dot product)

In [38]:
v1 = np.array([1,1,1])
v2 = np.array([2,-2,1])
np.dot(v1,v2.T)

1

1\*2 + 1\*-2 + 1\*1 = 1

#### With matrices

* Has to be a m\*n matrix by a n\*k matrix
* Result is m\*k matrix
* Multiply each row vector by each column vector

In [42]:
np.dot(m1,m2.T)

array([[183,  51],
       [ 71,  79]])